# Generated by Django 3.0.5 on 2020-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200417_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default=1, max_length=150, unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
