# Generated by Django 3.0.5 on 2020-04-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200423_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
    ]
