# Generated by Django 3.0.5 on 2020-04-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='product',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='value',
        ),
    ]
