# Generated by Django 3.0.5 on 2020-04-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productfeaturevalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeaturevalue',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товаров'},
        ),
    ]
