# Generated by Django 3.0.5 on 2020-05-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['count'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
